name: Pre-production Deployment

on:
  push:
    branches:
      - preprod  # Trigger on push to the `preprod` branch

jobs:
  deploy-to-preprod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Vercel CLI
        run: npm install -g vercel
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy to Pre-production
        run: |
          echo "Deploying to Pre-production environment..."
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}