name: Pre-production Deployment

on:
  # Add workflow_dispatch to enable manual triggers
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Deployment message'
        required: false
        default: 'Manual deployment to preprod'
  # Keep existing push trigger
  push:
    branches:
      - preprod

jobs:
  deploy-to-preprod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: qa  # This will checkout the QA branch
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Vercel CLI
        run: npm install -g vercel
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy to Pre-production
        run: |
          echo "Deploying to Pre-production environment..."
          echo "Deployment message: ${{ github.event.inputs.deploy_message || 'Push triggered deployment' }}"
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}