name: Production Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the `main` branch

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production  # Add production environment for extra protection
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Vercel CLI
        run: npm install -g vercel
      
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy to Production
        run: |
          echo "Deploying to Production environment..."
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}